### ISSUE TITLE
docker tags 

### ISSUE THREAD

**Issue by lsandini** [mt5h/ContainerDirectRouting#1]
Ciao Marco !

Little shell question in english, probably not an issue, but is this related to my git version or installation ?

I tried your solution in my win10/WSL2(ubuntu20.04) environment, and I had to modify line 5 of build_project.sh, otherwise I got an error about tags. Using Docker desktop 1.25.2.

I understand that the "which git" command exit code should be 0 and be discarded, but in my case **it is 0** and the script goes to line 10. 

which git returns   /usr/bin/git   btw.

I had to modify line 5 as below, in order for the script to execute line 7, etc...

```
which git > /dev/null 2>&1
if [[ $? -ne  0 ]]; ...
```

into 

```
which git > /dev/null 2>&1
if [[ $? ==  0 ]]; ...
```
Then it would work.

Lorenzo

**Comment by mt5h** [comment]
Ciao Lorenzo,

thanks for your feedback, really appreciated. I fixed the issue with the tag detection handling in the case where the tag is missing.

Please let me know if this commit solves the issue. 

Marco

**Comment by lsandini** [comment]
Nice, thanks ! Solved.

Strange that "git describe ... " found the tag correctly, but when $tag was added to the docker built command, I got the error. 
 
```
docker build -t spawner:$tag -f ./spawner/Dockerfile .
```
Anyway, the new version works now !
L.
